// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


INT ADD_TEN(INT X) {
		return (X) +((10)) ;
}
void PROGRAM_P(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(0, (0));
		gvl.write<INT>(2, (0));
		INT A = (1);
		for( ; A <= (5);A = A + (1)){
		INT _X0=gvl.read<INT>(0);
		gvl.write<INT>(2, ADD_TEN(_X0));
		}
}