#!/usr/bin/env pwsh
<#
.SYNOPSIS
    ST2C Build Script — compile ST → C++, link with flat runtime
.DESCRIPTION
    Reads tasks.json, compiles each .st source with the Java compiler,
    generates a POU registry aggregator, and links everything into an EXE.
.PARAMETER TasksJson
    Path to tasks.json (default: tasks.json in project root)
.PARAMETER Run
    If set, runs the resulting EXE after building
#>
param(
    [string]$TasksJson = "",
    [switch]$Run
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path "$PSScriptRoot"
if (-not $TasksJson) { $TasksJson = "$Root\tasks.json" }

$C_RST = "$([char]27)[0m"
$C_RED = "$([char]27)[31m"
$C_GRN = "$([char]27)[32m"
$C_YLW = "$([char]27)[33m"
$C_CYN = "$([char]27)[36m"
$C_BLD = "$([char]27)[1m"

Write-Host "${C_CYN}═══════════════════════════════════════════${C_RST}"
Write-Host "${C_CYN}  ST2C Build System${C_RST}"
Write-Host "${C_CYN}═══════════════════════════════════════════${C_RST}"

# ═══ Read tasks.json ═══
if (-not (Test-Path $TasksJson)) {
    Write-Host "${C_RED}[ERROR] tasks.json not found: $TasksJson${C_RST}"
    exit 1
}

$taskCfg = Get-Content $TasksJson -Raw | ConvertFrom-Json
$sources = @($taskCfg.sources)
$tasks = @($taskCfg.tasks)

if ($sources.Count -eq 0) {
    Write-Host "${C_RED}[ERROR] No sources defined in $TasksJson${C_RST}"
    exit 1
}

Write-Host "`n${C_BLD}Configuration:${C_RST}"
Write-Host "  sources: $($sources -join ', ')"
Write-Host "  tasks:   $($tasks.Count)"
Write-Host ""

# ═══ Java classpath ═══
$JavaDir = "$Root\java"
$TargetDir = "$JavaDir\target\classes"
$M2 = "$env:USERPROFILE\.m2\repository"
$ClassPath = @(
    $TargetDir
    "$M2\org\antlr\antlr4-runtime\4.10.1\antlr4-runtime-4.10.1.jar"
    "$M2\org\reflections\reflections\0.10.2\reflections-0.10.2.jar"
    "$M2\com\google\code\gson\gson\2.9.0\gson-2.9.0.jar"
    "$M2\org\javassist\javassist\3.28.0-GA\javassist-3.28.0-GA.jar"
    "$M2\org\slf4j\slf4j-api\1.7.32\slf4j-api-1.7.32.jar"
    "$M2\org\slf4j\slf4j-simple\1.7.32\slf4j-simple-1.7.32.jar"
) -join ";"

$BuildDir = "$Root\output\flat\build"
$RuntimeDir = "$Root\runtime-flat"
$IncDir = "$RuntimeDir\include"

# ═══ Step 1: Build Java compiler ═══
Write-Host "${C_BLD}[1/4] Building Java compiler...${C_RST}"
Push-Location $JavaDir
& "mvn.cmd" compile -q 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "${C_RED}[ERROR] Java build failed${C_RST}"
    Pop-Location; exit 1
}
Pop-Location
Write-Host "       ${C_GRN}OK${C_RST}"

# ═══ Step 2: Compile each ST source ═══
Write-Host "`n${C_BLD}[2/4] Compiling ST sources...${C_RST}"
New-Item -ItemType Directory -Path $BuildDir -Force | Out-Null

$compiledFiles = @()
foreach ($src in $sources) {
    $srcPath = if ([System.IO.Path]::IsPathRooted($src)) { $src } else { Join-Path $Root $src }
    $fileId = [System.IO.Path]::GetFileNameWithoutExtension($src)
    $outCpp = "$BuildDir\$fileId.cpp"

    Write-Host "  ${C_YLW}$fileId${C_RST} ... " -NoNewline
    $transOut = & java -cp "$ClassPath" Main --input "$srcPath" --output "$outCpp" 2>&1
    if ($LASTEXITCODE -eq 0 -and (Test-Path $outCpp)) {
        Write-Host "${C_GRN}OK${C_RST}"
        $compiledFiles += @{ FileId = $fileId; Cpp = $outCpp }
    } else {
        Write-Host "${C_RED}FAIL${C_RST}"
        Write-Host "    $($transOut -join '; ')"
    }
}

if ($compiledFiles.Count -eq 0) {
    Write-Host "${C_RED}[ERROR] No sources compiled successfully${C_RST}"
    exit 1
}

# ═══ Step 3: Generate pou_registry.gen.cpp ═══
Write-Host "`n${C_BLD}[3/4] Generating POU registry...${C_RST}"
$regCpp = "$BuildDir\pou_registry.gen.cpp"
$sb = [System.Text.StringBuilder]::new()
$sb.AppendLine("// Auto-generated by build.ps1")
$sb.AppendLine("#include `"rt_runtime.h`"")
$sb.AppendLine("")
$sb.AppendLine("using namespace rt_plc;")
$sb.AppendLine("")

# Forward declarations
foreach ($f in $compiledFiles) {
    $sb.AppendLine("extern void registerPOU_$($f.FileId)(POURegistry& reg);")
}
$sb.AppendLine("")

# Aggregator
$sb.AppendLine("void registerAllPOUs(POURegistry& reg) {")
foreach ($f in $compiledFiles) {
    $sb.AppendLine("    registerPOU_$($f.FileId)(reg);")
}
$sb.AppendLine("}")

Set-Content -Path $regCpp -Value $sb.ToString() -Encoding ASCII
Write-Host "       ${C_GRN}Generated: pou_registry.gen.cpp${C_RST}"

# ═══ Step 4: Compile + Link ═══
Write-Host "`n${C_BLD}[4/4] Compiling C++ and linking...${C_RST}"
$runtimeSrcs = @(
    "$RuntimeDir\src\gvl.cpp"
    "$RuntimeDir\src\program.cpp"
    "$RuntimeDir\src\task.cpp"
    "$RuntimeDir\src\event.cpp"
    "$RuntimeDir\src\watchdog.cpp"
    "$RuntimeDir\src\diag.cpp"
    "$RuntimeDir\src\scheduler.cpp"
)

$allCppFiles = @($regCpp) + ($compiledFiles | ForEach-Object { $_.Cpp })
$allSrcs = @("$RuntimeDir\runtime_main.cpp") + $allCppFiles + $runtimeSrcs
$outExe = "$BuildDir\runtime.exe"

$gpp = "g++"
$gppArgs = @("-std=c++17", "-I", "$IncDir", "-O2", "-o", "$outExe", "-x", "c++")
foreach ($s in $allSrcs) { $gppArgs += $s }

$compileOut = & $gpp $gppArgs 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "${C_RED}[ERROR] C++ compilation failed${C_RST}"
    Write-Host "$compileOut"
    exit 1
}

Write-Host "       ${C_GRN}OK → $outExe${C_RST}"
Write-Host ""

# ═══ Run ═══
if ($Run) {
    Write-Host "${C_BLD}Running...${C_RST}"
    Write-Host "────────────────────────────────────────"
    Push-Location $Root
    & $outExe
    Pop-Location
}

Write-Host ""
Write-Host "${C_GRN}Build complete.${C_RST}"
exit 0
