// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct MY_FB {
    INT X; // = (*(new INT(0)))
    INT Y; // = (*(new INT(0)))
    INT GLOBAL_COUNTER; // = (*(new INT(0)))

    void update() {

		Y = (X) +(GLOBAL_COUNTER) ;
		GLOBAL_COUNTER = (GLOBAL_COUNTER) +((1)) ;
    }
};

void PROGRAM_MAIN_init(GVL& gvl, ProcessImage& io) {
		gvl.write<INT>(0, (100));
		gvl.write<INT>(12, (0));
}
void PROGRAM_MAIN_pre(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_MAIN_cyclic(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(6, (10));
		gvl.ptr<MY_FB>(6)->update();
		gvl.write<INT>(12, (gvl.read<MY_FB>(6).Y));
}
void PROGRAM_MAIN_post(GVL& gvl, ProcessImage& io) {
}

// ─── Auto-generated POU Registration (test_fb_var_external) ───
void registerPOU_test_fb_var_external(POURegistry& reg) {
    POUCallbacks cbs;
    cbs.init = PROGRAM_MAIN_init;
    cbs.cyclic = PROGRAM_MAIN_cyclic;
    cbs.pre = PROGRAM_MAIN_pre;
    cbs.post = PROGRAM_MAIN_post;
    reg.add("MAIN", cbs);
}
