package PLCTranslator.TranslateType;

import PLCSymbolAndScope.PLCSymbols.PLCInterfaceDeclSymbol;
import PLCSymbolAndScope.PLCSymbols.PLCSymbol;
import PLCSymbolAndScope.PLCSymbols.PLCTypeDeclSymbol;
import PLCTranslator.PLCTranslatorNew;
import antlr4.PLCSTPARSERParser;

import java.util.ArrayList;

public class TranslateStartpoint {
    public static ArrayList<String> funcInitSentences = new ArrayList<>();

    public String translateNode(PLCSTPARSERParser.StartpointContext ctx, PLCTranslatorNew translatorNew){
        StringBuilder sb = new StringBuilder();
        if (translatorNew.shouldEmitHeader()) {
            sb.append("// Generated by ST2C++ (Flat backend)\n"
                    + "#include \"rt_plc.h\"\n"
                    + "#include \"rt_runtime.h\"\n"
                    + "\nusing namespace rt_plc;\n\n");
        }
        for (int i = 0; i < ctx.getChildCount(); i++) {
            String result = translatorNew.visit(ctx.getChild(i));
            if (result != null) {
                sb.append(result);
            }
        }
        if (translatorNew.shouldEmitPOURegistration()) {
            String fileId = PLCTranslatorNew.gvlCtx.getFileId();
            java.util.List<String> progNames = PLCTranslatorNew.gvlCtx.getProgramNames();
            if (progNames != null && !progNames.isEmpty()) {
                sb.append("\n// ─── Auto-generated POU Registration (").append(fileId).append(") ───\n");
                sb.append("void registerPOU_").append(fileId).append("(POURegistry& reg) {\n");
                for (String name : progNames) {
                    String mangled = fileId.isEmpty() ? name : fileId + "_" + name;
                    sb.append("    POUCallbacks cbs;\n");
                    sb.append("    cbs.init = PROGRAM_").append(mangled).append("_init;\n");
                    sb.append("    cbs.cyclic = PROGRAM_").append(mangled).append("_cyclic;\n");
                    sb.append("    cbs.pre = PROGRAM_").append(mangled).append("_pre;\n");
                    sb.append("    cbs.post = PROGRAM_").append(mangled).append("_post;\n");
                    sb.append("    reg.add(\"").append(name).append("\", cbs);\n");
                }
                sb.append("}\n");
            }
        }
        return sb.toString();
    }
}
