// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


void PROGRAM_P_init(GVL& gvl, ProcessImage& io) {
		gvl.write<INT>(0, (42));
		gvl.write<INT>(2, (0));
		gvl.write<INT>(4, (0));
}
void PROGRAM_P_pre(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_P_cyclic(GVL& gvl, ProcessImage& io, TIME dt) {
		printf("=== ASSERT Test ===");
		printf("\n");
		{ bool _st_assert = ((gvl.read<INT>(0)) ==((42)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 10)\n");
		  else
		    printf("  [FAIL] assert (line 10): A=42\n"); }
		{ bool _st_assert = ((gvl.read<INT>(0)) !=((0)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 11)\n");
		  else
		    printf("  [FAIL] assert (line 11): A<>0\n"); }
		{ bool _st_assert = ((gvl.read<INT>(2)) ==((0)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 12)\n");
		  else
		    printf("  [FAIL] assert (line 12): B=0\n"); }
		{ bool _st_assert = (((gvl.read<INT>(0)) +(gvl.read<INT>(2)) ) ==(gvl.read<INT>(0)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 13)\n");
		  else
		    printf("  [FAIL] assert (line 13): A+B=A\n"); }
		{ bool _st_assert = ((gvl.read<INT>(0)) ==((42)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 14)\n");
		  else
		    printf("  [FAIL] assert (line 14): A=42\n"); }
		{ bool _st_assert = ((gvl.read<INT>(0)) >(gvl.read<INT>(2)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 15)\n");
		  else
		    printf("  [FAIL] assert (line 15): A>B\n"); }
		{ bool _st_assert = (((10)) >((5)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 16)\n");
		  else
		    printf("  [FAIL] assert (line 16): 10>5\n"); }
		{ bool _st_assert = ((gvl.read<INT>(2)) ==((0)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 17)\n");
		  else
		    printf("  [FAIL] assert (line 17): B=0\n"); }
		gvl.write<INT>(4, (gvl.read<INT>(0)) +((10)) );
		{ bool _st_assert = ((gvl.read<INT>(4)) ==((52)) );
		  if (_st_assert)
		    printf("  [PASS] assert (line 20)\n");
		  else
		    printf("  [FAIL] assert (line 20): C=52\n"); }
		printf("Done");
		printf("\n");
}
void PROGRAM_P_post(GVL& gvl, ProcessImage& io) {
}

// ─── Auto-generated POU Registration (test_assert) ───
void registerPOU_test_assert(POURegistry& reg) {
    POUCallbacks cbs;
    cbs.init = PROGRAM_P_init;
    cbs.cyclic = PROGRAM_P_cyclic;
    cbs.pre = PROGRAM_P_pre;
    cbs.post = PROGRAM_P_post;
    reg.add("P", cbs);
}
