// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct MY_TIMER {
    INT ET; // = (*(new INT(0)))
    BOOL RUNNING; // = (*(new BOOL(FALSE)))
    INT ELAPSED; // = (*(new INT(0)))
    BOOL START; // = (*(new BOOL(false)))
    INT PT; // = (*(new INT(0)))
    BOOL Q; // = (*(new BOOL(false)))

    void update() {

		if((START) & (( ! RUNNING)) ){
		RUNNING = (true);
		ELAPSED = (0);
		}
		if(RUNNING){
		ELAPSED = (ELAPSED) +((1)) ;
		if((ELAPSED) >=(PT) ){
		Q = (true);
		}
		}
		ET = ELAPSED;
    }
};

void PROGRAM_test_fb_instantiate_MAIN_init(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_test_fb_instantiate_MAIN_pre(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_test_fb_instantiate_MAIN_cyclic(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<BOOL>(6, (true));
		gvl.write<INT>(8, (5));
		gvl.ptr<MY_TIMER>(0)->update();
		gvl.ptr<MY_TIMER>(0)->update();
}
void PROGRAM_test_fb_instantiate_MAIN_post(GVL& gvl, ProcessImage& io) {
}

// ─── Auto-generated POU Registration (test_fb_instantiate) ───
void registerPOU_test_fb_instantiate(POURegistry& reg) {
    POUCallbacks cbs;
    cbs.init = PROGRAM_test_fb_instantiate_MAIN_init;
    cbs.cyclic = PROGRAM_test_fb_instantiate_MAIN_cyclic;
    cbs.pre = PROGRAM_test_fb_instantiate_MAIN_pre;
    cbs.post = PROGRAM_test_fb_instantiate_MAIN_post;
    reg.add("MAIN", cbs);
}
