// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct MY_COUNTER {
    INT CV; // = (*(new INT(0)))
    BOOL PREV_CLK; // = (*(new BOOL(FALSE)))
    INT COUNT; // = (*(new INT(0)))
    BOOL CLK; // = (*(new BOOL(false)))
    BOOL RESET; // = (*(new BOOL(false)))
    BOOL Q; // = (*(new BOOL(false)))

    void update() {

		Q = (false);
		if(RESET){
		COUNT = (0);
		}else if((CLK) & (( ! PREV_CLK)) ){
		COUNT = (COUNT) +((1)) ;
		}
		PREV_CLK = CLK;
		CV = COUNT;
		if((COUNT) >=((5)) ){
		Q = (true);
		}
    }
};

