// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


SINT DINT_TO_TIME(DINT IN);

DINT UDINT_TO_DINT(UDINT IN);

SINT INT_TO_UDINT(INT IN);

SINT UDINT_TO_TIME(UDINT IN);

SINT DINT_TO_UDINT(DINT IN);

SINT TIME_TO_UDINT(TIME IN);

DINT REAL_TO_DINT(REAL IN);

SINT REAL_TO_UDINT(REAL IN);

SINT REAL_TO_DWORD(REAL IN);

INT REAL_TO_INT(REAL IN);

SINT REAL_TO_WORD(REAL IN);

SINT REAL_TO_BYTE(REAL IN);

SINT REAL_TO_TIME(REAL IN);

STRING REAL_TO_STRF(REAL IN);

STRING REAL_TO_STRING(REAL IN);

DINT INT_TO_DINT(INT IN);

REAL INT_TO_REAL(INT IN);

SINT INT_TO_DWORD(INT IN);

SINT INT_TO_BYTE(INT IN);

SINT INT_TO_WORD(INT IN);

STRING INT_TO_STRING(INT IN);

SINT INT_TO_TIME(INT IN);

SINT INT_TO_UINT(INT IN);

INT DINT_TO_INT(DINT IN);

REAL DINT_TO_REAL(DINT IN);

SINT DINT_TO_DWORD(DINT IN);

SINT DINT_TO_WORD(DINT IN);

STRING DINT_TO_STRING(DINT IN);

DINT DWORD_TO_DINT(DWORD IN);

INT DWORD_TO_INT(DWORD IN);

SINT DWORD_TO_WORD(DWORD IN);

SINT DWORD_TO_BYTE(DWORD IN);

SINT DWORD_TO_TIME(DWORD IN);

SINT DWORD_TO_UDINT(DWORD IN);

STRING DWORD_TO_STRING(DWORD IN);

STRING DWORD_TO_STRB(DWORD IN);

STRING DWORD_TO_STRH(DWORD IN);

STRING DWORD_TO_STRF(DWORD IN);

REAL DW_TO_REAL(DWORD IN);

REAL UDINT_TO_REAL(UDINT IN);

INT UDINT_TO_INT(UDINT IN);

SINT UDINT_TO_DWORD(UDINT IN);

SINT UDINT_TO_WORD(UDINT IN);

SINT UDINT_TO_BYTE(UDINT IN);

STRING UDINT_TO_STRING(UDINT IN);

SINT UDINT_TO_UINT(UDINT IN);

DINT WORD_TO_DINT(WORD IN);

INT WORD_TO_INT(WORD IN);

SINT WORD_TO_DWORD(WORD IN);

SINT WORD_TO_BYTE(WORD IN);

SINT WORD_TO_UDINT(WORD IN);

SINT WORD_TO_UINT(WORD IN);

STRING WORD_TO_STRING(WORD IN);

DINT BYTE_TO_DINT(BYTE IN);

INT BYTE_TO_INT(BYTE IN);

SINT BYTE_TO_DWORD(BYTE IN);

SINT BYTE_TO_WORD(BYTE IN);

SINT BYTE_TO_UDINT(BYTE IN);

SINT BYTE_TO_UINT(BYTE IN);

SINT BYTE_TO_USINT(BYTE IN);

STRING BYTE_TO_STRING(BYTE IN);

STRING BYTE_TO_STRB(BYTE IN);

STRING BYTE_TO_STRH(BYTE IN);

STRING BYTE_TO_BITS(BYTE IN);

SINT BYTE_TO_GRAY(BYTE IN);

SINT BYTE_TO_TIME2(BYTE IN);

DINT UINT_TO_DINT(UINT IN);

INT UINT_TO_INT(UINT IN);

SINT UINT_TO_DWORD(UINT IN);

SINT UINT_TO_BYTE(UINT IN);

SINT UINT_TO_WORD(UINT IN);

SINT UINT_TO_UDINT(UINT IN);

REAL UINT_TO_REAL(UINT IN);

INT USINT_TO_INT(USINT IN);

SINT USINT_TO_BYTE(USINT IN);

REAL USINT_TO_REAL(USINT IN);

DINT USINT_TO_DINT(USINT IN);

INT SINT_TO_INT(SINT IN);

DINT SINT_TO_DINT(SINT IN);

SINT STRING_TO_TIME(STRING IN);

INT STRING_TO_INT(STRING IN);

REAL STRING_TO_REAL(STRING IN);

SINT STRING_TO_DWORD(STRING IN);

SINT STRING_TO_WORD(STRING IN);

SINT STRING_TO_UDINT(STRING IN);

STRING STRING_TO_URL(STRING IN);

STRING STRING_TO_BUFFER(STRING IN);

SINT BOOL_TO_BYTE(BOOL IN);

INT BOOL_TO_INT(BOOL IN);

SINT BOOL_TO_DWORD(BOOL IN);

SINT BOOL_TO_UDINT(BOOL IN);

STRING BOOL_TO_STRING(BOOL IN);

DINT TIME_TO_DINT(TIME IN);

INT TIME_TO_INT(TIME IN);

SINT TIME_TO_DWORD(TIME IN);

REAL TIME_TO_REAL(TIME IN);

STRING TIME_TO_TOD(TIME IN);

SINT TOD_TO_TIME(STRING IN);

REAL TOD_TO_REAL2(STRING IN);

SINT DATE_TO_UDINT(INT IN);

INT DATE_TO_DT(INT IN);

STRING DATE_TO_STRING2(INT IN);

REAL DATE_TO_REAL2(INT IN);

SINT DATE_TO_DWORD2(INT IN);

INT DT_TO_DATE(INT IN);

INT DT_TO_DATE2(INT IN);

STRING DT_TO_TOD2(INT IN);

INT DT_TO_SDT(INT IN);

STRING DT_TO_STRF(INT IN);

INT SDT_TO_DATE(INT IN);

INT SDT_TO_DT(INT IN);

STRING SDT_TO_TOD(INT IN);

STRING CONCAT(STRING A, STRING B);

DINT LEN(STRING S);

STRING LEFT(STRING S, DINT L);

STRING RIGHT(STRING S, DINT L);

STRING MID(STRING S, DINT L, DINT P);

STRING INSERT(STRING S, STRING INS, DINT P);

STRING DELETE(STRING S, DINT L, DINT P);

STRING REPLACE(STRING S, DINT L, DINT P, STRING R);

DINT FIND(STRING S, STRING SUBSTR);

BOOL STR_EQ(STRING A, STRING B);

BOOL STR_NE(STRING A, STRING B);

BOOL STR_LT(STRING A, STRING B);

BOOL STR_LE(STRING A, STRING B);

BOOL STR_GT(STRING A, STRING B);

BOOL STR_GE(STRING A, STRING B);

REAL ABS(REAL X);

REAL SQRT(REAL X);

REAL LN(REAL X);

REAL LOG(REAL X);

REAL EXP(REAL X);

REAL EXPT(REAL X, REAL Y);

REAL SIN(REAL X);

REAL COS(REAL X);

REAL TAN(REAL X);

REAL ASIN(REAL X);

REAL ACOS(REAL X);

REAL ATAN(REAL X);

REAL ATAN2(REAL Y, REAL X);

REAL SEL(BOOL G, REAL IN0, REAL IN1);

REAL MUX(INT K, REAL IN0, REAL IN1, REAL IN2, REAL IN3);

REAL LIMIT(REAL MN, REAL IN, REAL MX);

REAL MAX(REAL IN0, REAL IN1);

REAL MIN(REAL IN0, REAL IN1);


enum class DIRECTION : INT {
    NORTH,
    EAST,
    SOUTH,
    WEST
};

struct MATRIX_ROW {
    INT VALUES[4];
    INT TAG;
};

DINT DOUBLE_IT(INT X) {
		return (X) *((2)) ;
}
DINT CLAMP(DINT VAL, DINT MINV, DINT MAXV) {
		if((VAL) <(MINV) ){
		return MINV;
		}else if((VAL) >(MAXV) ){
		return MAXV;
		}else{
		return VAL;
		}
}
INT WRAP_ANGLE(INT ANGLE) {
		while((ANGLE) <((0)) ){
		ANGLE = (ANGLE) +((360)) ;
		}
		while((ANGLE) >=((360)) ){
		ANGLE = (ANGLE) -((360)) ;
		}
		return ANGLE;
}
REAL AVERAGE(REAL A, REAL B) {
		return (((A) +(B) )) /((2.0)) ;
}
struct STATE_MACHINE {
    INT CMD; // = 0
    DINT POSITION; // = 0
    INT DIR;
    INT SPEED; // = 0
    BOOL FAULT; // = false
    INT MODE; // = (0)
    DINT ACCUM; // = (0)
    BOOL RUNNING; // = (*(new BOOL(FALSE)))
    INT RETRY; // = (0)

    void update() {

		FAULT = (*(new BOOL(FALSE)));
		RUNNING = (*(new BOOL(TRUE)));
if((CMD==(0))){
		MODE = (0);
		ACCUM = (0);
		SPEED = (0);
		DIR = 0;
		RUNNING = (*(new BOOL(FALSE)));}
else if((CMD==(1))
){
		MODE = (10);
		ACCUM = (0);
		DIR = 0;
}
else if((CMD==(2))
){
		MODE = (20);
		ACCUM = (0);
		DIR = 0;
}
else if((CMD==(3))
){
		MODE = (30);
		DIR = 0;
}
else if((CMD==(10))
){
		MODE = (0);
		FAULT = (*(new BOOL(TRUE)));
		}else{
		MODE = (99);
		FAULT = (*(new BOOL(TRUE)));
}
		if(RUNNING){
if((MODE==(10))){
		ACCUM = (ACCUM) +(POSITION) ;
		if((ACCUM) >=((1000)) ){
		MODE = (11);
		}}
else if((MODE==(20))
){
		ACCUM = (ACCUM) -(POSITION) ;
		if((ACCUM) <=((-1000)) ){
		MODE = (21);
		}
}
else if((MODE==(30))
){
		SPEED = (0);
		RETRY = (RETRY) +((1)) ;
		if((RETRY) >=((3)) ){
		MODE = (31);
		}
}
else if((MODE==(11))
||(MODE==21)
||(MODE==31)
){
		SPEED = (0);
		RUNNING = (*(new BOOL(FALSE)));
}
else{}
		}
    }
};

void PROGRAM_test_tricky_TRICKY_MAIN_init(GVL& gvl, ProcessImage& io) {
		gvl.write<INT>(30, (0));
		gvl.write<INT>(32, (0));
		gvl.write<DINT>(36, (0));
		gvl.write<DINT>(40, (0));
		gvl.write<INT>(44, (-450));
		gvl.write<INT>(46, (0));
		gvl.write<REAL>(48, (0.0));
		gvl.write<DINT>(52, (0));
		gvl.write<DINT>(56, (0));
		gvl.write<INT>(96, (0));
		gvl.write<BOOL>(98, (*(new BOOL(FALSE))));
		gvl.write<INT>(124, (0));
		gvl.write<DINT>(128, (0));
}
void PROGRAM_test_tricky_TRICKY_MAIN_pre(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_test_tricky_TRICKY_MAIN_cyclic(GVL& gvl, ProcessImage& io, TIME dt) {
		printf("=== TRICKY TEST START ===");
		printf("\n");
		INT I = (0);
		for( ; I <= (2);I = I + (1)){
		(gvl.safeArrayAt<MATRIX_ROW>(0, I, 3).TAG) = (I) *((100)) ;
		INT J = (0);
		for( ; J <= (3);J = J + (1)){
		(gvl.safeArrayAt<MATRIX_ROW>(0, I, 3).VALUES[J]) = (((I) *((10)) )) +(J) ;
		gvl.write<DINT>(36, (gvl.read<DINT>(36)) +((gvl.safeArrayAt<MATRIX_ROW>(0, I, 3).VALUES[J])) );
		}
		gvl.write<INT>(32, J);
		}
		gvl.write<INT>(30, I);
		printf("TOTAL = ");
		printf("%d", (int)(gvl.read<DINT>(36)));
		printf("\n");
		INT _ANGLE0=gvl.read<INT>(44);
		gvl.write<INT>(46, WRAP_ANGLE(_ANGLE0));
		printf("WRAPPED = ");
		printf("%d", (int)(gvl.read<INT>(46)));
		printf("\n");
		REAL _A1=(10.5);
		REAL _B2=(20.5);
		gvl.write<REAL>(48, AVERAGE(_A1, _B2));
		printf("AVG = ");
		printf("%d", (int)(gvl.read<REAL>(48)));
		printf("\n");
		INT _VAL3=(-100);
		INT _MINV4=(0);
		INT _MAXV5=(50);
		gvl.write<DINT>(52, CLAMP(_VAL3, _MINV4, _MAXV5));
		printf("CLAMPED = ");
		printf("%d", (int)(gvl.read<DINT>(52)));
		printf("\n");
		INT _VAL6=(999);
		INT _MINV7=(0);
		INT _MAXV8=(100);
		gvl.write<DINT>(56, CLAMP(_VAL6, _MINV7, _MAXV8));
		printf("CLAMPED2 = ");
		printf("%d", (int)(gvl.read<DINT>(56)));
		printf("\n");
		gvl.write<INT>(96, (1));
		gvl.write<INT>(72, gvl.read<INT>(96));
		gvl.write<DINT>(76, (500));
		gvl.ptr<STATE_MACHINE>(72)->update();
		gvl.write<INT>(96, (2));
		gvl.write<INT>(72, gvl.read<INT>(96));
		gvl.write<DINT>(76, (1200));
		gvl.ptr<STATE_MACHINE>(72)->update();
		gvl.write<INT>(96, (3));
		gvl.write<INT>(72, gvl.read<INT>(96));
		gvl.write<DINT>(76, (-800));
		gvl.ptr<STATE_MACHINE>(72)->update();
		gvl.write<INT>(124, (0));
		do{
		INT _X15=(gvl.read<INT>(124)) *((10)) ;
		(gvl.safeArrayAt<DINT>(100, gvl.read<INT>(124), 6)) = DOUBLE_IT(_X15);
		gvl.write<INT>(124, (gvl.read<INT>(124)) +((1)) );
		}while(!((gvl.read<INT>(124)) >=((6)) ));
		gvl.write<DINT>(128, (42));
		printf("RESULT_ARR[3] = ");
		printf("%d", (int)(gvl.read<DINT>(128)));
		printf("\n");
		gvl.write<BOOL>(98, ((((gvl.read<INT>(30)) >=((2)) )) & (((gvl.read<DINT>(36)) >((0)) )) ) || (((gvl.read<INT>(46)) !=((270)) )));
		if((gvl.read<BOOL>(98)) & (( ! ((gvl.read<DINT>(52)) <((0)) ))) ){
		printf("FLAG IS TRUE");
		printf("\n");
		}
		gvl.write<DINT>(40, (0));
		while((gvl.read<DINT>(40)) <((10)) ){
		gvl.write<DINT>(40, (gvl.read<DINT>(40)) +((1)) );
		if((gvl.read<DINT>(40)) ==((5)) ){
		gvl.write<DINT>(40, (10));
		}
		}
		printf("COUNT = ");
		printf("%d", (int)(gvl.read<DINT>(40)));
		printf("\n");
		{ bool _st_assert = ((gvl.read<DINT>(36)) ==((66)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 224)\n");
		  else
		    printf("  [FAIL] assert (line 224): TOTAL=66\n"); }
		{ bool _st_assert = ((gvl.read<INT>(46)) ==((270)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 225)\n");
		  else
		    printf("  [FAIL] assert (line 225): WRAPPED=270\n"); }
		{ bool _st_assert = ((gvl.read<DINT>(52)) ==((50)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 226)\n");
		  else
		    printf("  [FAIL] assert (line 226): CLAMPED=50\n"); }
		{ bool _st_assert = ((gvl.read<REAL>(48)) >((15.0)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 227)\n");
		  else
		    printf("  [FAIL] assert (line 227): AVG>15.0\n"); }
		{ bool _st_assert = (((gvl.safeArrayAt<MATRIX_ROW>(0, 0, 3).TAG)) ==((0)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 228)\n");
		  else
		    printf("  [FAIL] assert (line 228): MATRIX[0].TAG=0\n"); }
		{ bool _st_assert = (((gvl.safeArrayAt<MATRIX_ROW>(0, 2, 3).VALUES[3])) ==((23)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 229)\n");
		  else
		    printf("  [FAIL] assert (line 229): MATRIX[2].VALUES[3]=23\n"); }
		{ bool _st_assert = ((gvl.read<INT>(124)) >=((6)) );
		  if(_st_assert)
		    printf("  [PASS] assert (line 230)\n");
		  else
		    printf("  [FAIL] assert (line 230): K>=6\n"); }
		{ bool _st_assert = (( ! gvl.read<BOOL>(98)));
		  if(_st_assert)
		    printf("  [PASS] assert (line 231)\n");
		  else
		    printf("  [FAIL] assert (line 231): NOTFLAG\n"); }
		printf("=== TRICKY TEST PASS ===");
		printf("\n");
}
void PROGRAM_test_tricky_TRICKY_MAIN_post(GVL& gvl, ProcessImage& io) {
}

// ─── Auto-generated POU Registration (test_tricky) ───
void registerPOU_test_tricky(POURegistry& reg) {
    POUCallbacks cbs;
    cbs.init = PROGRAM_test_tricky_TRICKY_MAIN_init;
    cbs.cyclic = PROGRAM_test_tricky_TRICKY_MAIN_cyclic;
    cbs.pre = PROGRAM_test_tricky_TRICKY_MAIN_pre;
    cbs.post = PROGRAM_test_tricky_TRICKY_MAIN_post;
    reg.add("TRICKY_MAIN", cbs);
}
