// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct MY_POINT {
    INT X;
    INT Y;
};

void PROGRAM_MAIN_init(GVL& gvl, ProcessImage& io) {
		gvl.write<INT>(20, (0));
		gvl.write<INT>(22, (0));
}
void PROGRAM_MAIN_pre(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_MAIN_cyclic(GVL& gvl, ProcessImage& io, TIME dt) {
		INT I = (0);
		for( ; I <= (4);I = I + (1)){
		gvl.safeArrayAt<MY_POINT>(0, I, 5).X = (I) *((10)) ;
		gvl.safeArrayAt<MY_POINT>(0, I, 5).Y = (I) *((20)) ;
		}
		gvl.write<INT>(20, I);
		gvl.write<INT>(22, ((gvl.safeArrayAt<MY_POINT>(0, 0, 5).X)) +((gvl.safeArrayAt<MY_POINT>(0, 1, 5).X)) );
}
void PROGRAM_MAIN_post(GVL& gvl, ProcessImage& io) {
}

// ─── Auto-generated POU Registration (test_arr_struct) ───
void registerPOU_test_arr_struct(POURegistry& reg) {
    POUCallbacks cbs;
    cbs.init = PROGRAM_MAIN_init;
    cbs.cyclic = PROGRAM_MAIN_cyclic;
    cbs.pre = PROGRAM_MAIN_pre;
    cbs.post = PROGRAM_MAIN_post;
    reg.add("MAIN", cbs);
}
