// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct MY_TIMER {
    INT ET; // = (*(new INT(0)))
    BOOL RUNNING; // = (*(new BOOL(FALSE)))
    INT ELAPSED; // = (*(new INT(0)))
    BOOL START; // = (*(new BOOL(false)))
    INT PT; // = (*(new INT(0)))
    BOOL Q; // = (*(new BOOL(false)))

    void update() {

		if((START) & (( ! RUNNING)) ){
		RUNNING = (true);
		ELAPSED = (0);
		}
		if(RUNNING){
		ELAPSED = (ELAPSED) +((1)) ;
		if((ELAPSED) >=(PT) ){
		Q = (true);
		}
		}
		ET = ELAPSED;
    }
};

