// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct ADVANCED_CTRL {
    INT STATUS; // = (*(new INT(0)))
    INT RESULT; // = (*(new INT(0)))
    BOOL BUSY; // = (*(new BOOL(false)))
    BOOL DONE; // = (*(new BOOL(false)))
    BOOL ERROR; // = (*(new BOOL(false)))
    INT STATE; // = (*(new INT(0)))
    INT ACCUM; // = (*(new INT(0)))
    INT CYCLE_CNT; // = (*(new INT(0)))
    INT CMD; // = (*(new INT(0)))
    INT VALUE; // = (*(new INT(0)))
    BOOL RESET; // = (*(new BOOL(false)))

    void update() {

		BUSY = (true);
		DONE = (false);
		ERROR = (false);
		if(RESET){
		STATE = (0);
		ACCUM = (0);
		CYCLE_CNT = (0);
		RESULT = (0);
		STATUS = (0);
		}else if((STATE) ==((0)) ){
		if((CMD) >((0)) ){
		STATE = (10);
		ACCUM = (0);
		}
		STATUS = (0);
		}else if((STATE) ==((10)) ){
		ACCUM = (ACCUM) +(VALUE) ;
		CYCLE_CNT = (CYCLE_CNT) +((1)) ;
		if((CYCLE_CNT) >=((5)) ){
		STATE = (20);
		RESULT = ACCUM;
		}
		STATUS = (1);
		}else if((STATE) ==((20)) ){
		DONE = (true);
		BUSY = (false);
		STATUS = (2);
		}else{
		STATE = (0);
		STATUS = (99);
		ERROR = (true);
		}
    }
};

