package PLCTranslator.TranslateType.Startpoint;

import PLCSymbolAndScope.PLCSymbols.PLCInterfaceDeclSymbol;
import PLCSymbolAndScope.PLCSymbols.PLCSymbol;
import PLCSymbolAndScope.PLCSymbols.PLCTypeDeclSymbol;
import PLCTranslator.PLCTranslatorNew;
import antlr4.PLCSTPARSERParser;

import java.util.ArrayList;

//PLCSt翻译起点
public class TranslateStartpoint {
    public static ArrayList<String> funcInitSentences = new ArrayList<>();

    public String translateNode(PLCSTPARSERParser.StartpointContext ctx, PLCTranslatorNew translatorNew){
        StringBuilder sb = new StringBuilder();
        if (translatorNew.shouldEmitHeader()) {
            sb.append("// Generated by ST2C++ (Flat backend)\n"
                    + "#include \"rt_plc.h\"\n"
                    + "#include \"rt_runtime.h\"\n"
                    + "\nusing namespace rt_plc;\n\n");
        }
        // 手动遍历子节点并拼接
        for (int i = 0; i < ctx.getChildCount(); i++) {
            String result = translatorNew.visit(ctx.getChild(i));
            if (result != null) {
                sb.append(result);
            }
        }
        if (translatorNew.shouldEmitPOURegistration()) {
            sb.append(PLCTranslatorNew.gvlCtx.emitPOURegistration(
                PLCTranslatorNew.gvlCtx.getFileId(), PLCTranslatorNew.gvlCtx.getProgramNames()));
        }
        return sb.toString();
    }
}
