// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


struct MY_POINT {
    INT X;
    INT Y;
};

void PROGRAM_MAIN(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(4, (0));
		gvl.write<INT>(0, (10));
		gvl.write<INT>(2, (20));
		gvl.write<INT>(4, ((gvl.read<MY_POINT>(0).X)) +((gvl.read<MY_POINT>(0).Y)) );
}