// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


void PROGRAM_P(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(10, (0));
		gvl.write<INT>(12, (0));
		gvl.write<INT>(12, (0));
		INT I = (0);
		for( ; I <= (4);I++){
		gvl.safeArrayAt<INT>(0, I, 5) = (I) *((10)) ;
		gvl.write<INT>(12, (gvl.read<INT>(12)) +((gvl.safeArrayAt<INT>(0, I, 5))) );
		}
		gvl.write<INT>(10, I);
}