// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


void PROGRAM_P_Binit(GVL& gvl, ProcessImage& io) {
		gvl.write<INT>(10, (0));
		gvl.write<INT>(12, (0));
}
void PROGRAM_P_Bpre(GVL& gvl, ProcessImage& io) {
}
void PROGRAM_P_Bcyclic(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(12, (0));
		INT I = (0);
		for( ; I <= (4);I++){
		gvl.safeArrayAt<INT>(0, I, 5) = (I) *((10)) ;
		gvl.write<INT>(12, (gvl.read<INT>(12)) +((gvl.safeArrayAt<INT>(0, I, 5))) );
		}
		gvl.write<INT>(10, I);
}
void PROGRAM_P_Bpost(GVL& gvl, ProcessImage& io) {
}
// ─── Auto-generated POU Registration (test_array) ───
void registerPOU_test_array(POURegistry& reg) {
    POUCallbacks cbs;
    cbs.init = PROGRAM_P_Binit;
    cbs.cyclic = PROGRAM_P_Bcyclic;
    cbs.pre = PROGRAM_P_Bpre;
    cbs.post = PROGRAM_P_Bpost;
    reg.add("PB", cbs);
}
