// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


INT PRINTF(STRING FMT);

void PROGRAM_MAIN(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(0, (42));
		gvl.write<INT>(2, (10));
		gvl.write<INT>(4, (0));
		gvl.write<INT>(4, (gvl.read<INT>(0)) +(gvl.read<INT>(2)) );
		printf("C = ");
		printf("%d", (int)(gvl.read<INT>(4)));
		printf("\n");
		printf("A = ");
		printf("%d", (int)(gvl.read<INT>(0)));
		printf("\n");
		printf("%d", (int)(gvl.read<INT>(2)));
		printf("\n");
		printf("%d", (int)(gvl.read<INT>(4)));
		printf("\n");
		if((gvl.read<INT>(4)) ==((52)) ){
		printf("%d", (int)(gvl.read<INT>(0)));
		printf("\n");
		}
}
// ─── Auto-generated POU Registration (test_print) ───
void registerPOU_test_print(POURegistry& reg) {
    reg.add("MAIN", PROGRAM_MAIN);
}
