// Generated by ST2C++ (Flat backend)
#include "rt_plc.h"
#include "rt_runtime.h"

using namespace rt_plc;


INT FUN(INT X) {
		if((*X) ==((*(new INT(2)))) ){
		*this->returnValue  = (*(new INT(1)));
		}else if((*X) ==((*(new INT(1)))) ){
		*this->returnValue  = (*(new INT(1)));
		}else{
		auto _X1=(*X) -((*(new INT(2)))) ;
		*this->returnValue  = (*::PLC::RFM->getSymbolByID<FUN*>(219)->callFunc(&_X0)) +(*::PLC::RFM->getSymbolByID<FUN*>(219)->callFunc(&_X1)) ;
		}
}
void PROGRAM_P(GVL& gvl, ProcessImage& io, TIME dt) {
		gvl.write<INT>(0, (*(new INT(10))));
		gvl.write<INT>(2, (*(new INT(0))));
		for( B = (*(new INT(10)));B <= (*(new INT(100)));B = B + (*(new INT(2)))){
		*A = (*A) +((*(new INT(20)))) ;
		}
		auto _X2=(*(new INT(10)));
		*B = *::PLC::RFM->getSymbolByID<FUN*>(219)->callFunc(&_X2);
}