package PLCTranslator;

import java.util.*;

import static PLCTargetFileOutPut.TargetFileOutput.writeTarget;

/**
 * Flat 后端 — 生成 GVL 偏移量风格的 C++ 代码
 *
 * 使用新版运行时 rt_plc.h + rt_runtime.h，
 * 变量通过偏移量直接读写 GVL 内存，零堆分配、零虚函数。
 */
public class FlatCodeGenerator implements CodeGenerator {

    // GVL 偏移量分配
    private final Map<String, Integer> offsetMap = new LinkedHashMap<>();
    private final Map<String, String> typeMap = new LinkedHashMap<>();
    private int currentOffset = 0;

    // ST 类型名 → 原生 C++ 类型名
    private static final Map<String, String> TYPE_MAP = new HashMap<>();
    static {
        TYPE_MAP.put("SINT", "SINT");
        TYPE_MAP.put("INT", "INT");
        TYPE_MAP.put("DINT", "DINT");
        TYPE_MAP.put("LINT", "LINT");
        TYPE_MAP.put("USINT", "USINT");
        TYPE_MAP.put("UINT", "UINT");
        TYPE_MAP.put("UDINT", "UDINT");
        TYPE_MAP.put("ULINT", "ULINT");
        TYPE_MAP.put("REAL", "REAL");
        TYPE_MAP.put("LREAL", "LREAL");
        TYPE_MAP.put("BOOL", "BOOL");
        TYPE_MAP.put("STRING", "STRING");
        TYPE_MAP.put("TIME", "TIME");
        TYPE_MAP.put("DATE", "DATE");
        TYPE_MAP.put("TIME_OF_DAY", "TIME_OF_DAY");
        TYPE_MAP.put("DATE_AND_TIME", "DATE_AND_TIME");
        // PLC_Value 风格的类型名也映射
        TYPE_MAP.put("PLC_SINT_Value", "SINT");
        TYPE_MAP.put("PLC_INT_Value", "INT");
        TYPE_MAP.put("PLC_DINT_Value", "DINT");
        TYPE_MAP.put("PLC_LINT_Value", "LINT");
        TYPE_MAP.put("PLC_Real_Value", "REAL");
        TYPE_MAP.put("PLC_LReal_Value", "LREAL");
        TYPE_MAP.put("PLC_Bool_Value", "BOOL");
        TYPE_MAP.put("PLC_String_Value", "STRING");
    }

    // 类型 → 字节大小
    private static final Map<String, Integer> SIZE_MAP = new HashMap<>();
    static {
        SIZE_MAP.put("SINT", 1);
        SIZE_MAP.put("INT", 2);
        SIZE_MAP.put("DINT", 4);
        SIZE_MAP.put("LINT", 8);
        SIZE_MAP.put("USINT", 1);
        SIZE_MAP.put("UINT", 2);
        SIZE_MAP.put("UDINT", 4);
        SIZE_MAP.put("ULINT", 8);
        SIZE_MAP.put("REAL", 4);
        SIZE_MAP.put("LREAL", 8);
        SIZE_MAP.put("BOOL", 1);
        SIZE_MAP.put("STRING", 256);
        SIZE_MAP.put("TIME", 8);
        SIZE_MAP.put("DATE", 4);
        SIZE_MAP.put("TIME_OF_DAY", 8);
        SIZE_MAP.put("DATE_AND_TIME", 8);
    }

    private String toNativeType(String typeName) {
        String mapped = TYPE_MAP.get(typeName);
        return mapped != null ? mapped : typeName;
    }

    private int getTypeSize(String nativeType) {
        Integer size = SIZE_MAP.get(nativeType);
        return size != null ? size : 4; // 默认 4 字节
    }

    /**
     * 为变量分配 GVL 偏移量
     */
    private int allocateOffset(String varName, String nativeType) {
        int size = getTypeSize(nativeType);
        // 对齐到类型大小
        int aligned = (currentOffset + size - 1) / size * size;
        offsetMap.put(varName, aligned);
        typeMap.put(varName, nativeType);
        currentOffset = aligned + size;
        return aligned;
    }

    /**
     * 获取变量的 GVL 读取表达式
     */
    private String readExpr(String varName) {
        String type = typeMap.get(varName);
        Integer offset = offsetMap.get(varName);
        if (type == null || offset == null) {
            // 未知变量，可能是临时变量或表达式结果，直接返回
            return varName;
        }
        return "gvl.read<" + type + ">(" + offset + ")";
    }

    /**
     * 获取变量的 GVL 写入语句前缀
     */
    private String writeExpr(String varName, String valueExpr) {
        String type = typeMap.get(varName);
        Integer offset = offsetMap.get(varName);
        if (type == null || offset == null) {
            return varName + " = " + valueExpr;
        }
        return "gvl.write<" + type + ">(" + offset + ", " + valueExpr + ")";
    }


    // ═══ 文件头尾 ═══

    @Override
    public void emitHeader() {
        writeTarget("// Generated by ST2C++ (Flat backend)\n");
        writeTarget("#include \"rt_plc.h\"\n");
        writeTarget("#include \"rt_runtime.h\"\n");
        writeTarget("\nusing namespace rt_plc;\n\n");
    }

    @Override
    public void emitFooter() {
        // Flat 模式不需要特殊清理
    }


    // ═══ 变量声明 ═══

    @Override
    public void emitVarDecl(String name, String typeName, String assignVar) {
        String nativeType = toNativeType(typeName);
        allocateOffset(name, nativeType);
        // Flat 模式：变量在 GVL 中，不需要 C++ 声明
        // 但如果需要初始化，生成初始化代码
        if (assignVar != null && !assignVar.isEmpty() && !"0".equals(assignVar) && !"\"\"".equals(assignVar)) {
            writeTarget("\n\t\t" + writeExpr(name, assignVar) + ";");
        }
    }

    @Override
    public void emitGlobalVarDecl(String name, String typeName, String assignVar, String varSection) {
        String nativeType = toNativeType(typeName);
        allocateOffset(name, nativeType);
        // 全局变量在 GVL 中，不需要 C++ 声明
    }

    @Override
    public void emitProgVarDecl(String name, String typeName, String assignVar) {
        String nativeType = toNativeType(typeName);
        allocateOffset(name, nativeType);
        // PROGRAM 变量在 GVL 中
    }


    // ═══ 赋值 ═══

    @Override
    public void emitAssign(String varName, String exprAssignVar) {
        writeTarget("\n\t\t" + writeExpr(varName, exprAssignVar) + ";");
    }

    @Override
    public void emitFuncReturnAssign(String exprAssignVar) {
        writeTarget("\n\t\treturn " + exprAssignVar + ";");
    }


    // ═══ 控制流 ═══

    @Override
    public void emitIfBegin(String condAssignVar) {
        writeTarget("\n\t\tif(" + condAssignVar + "){");
    }

    @Override
    public void emitElseIf(String condAssignVar) {
        writeTarget("\n\t\t}else if(" + condAssignVar + "){");
    }

    @Override
    public void emitElse() {
        writeTarget("\n\t\t}else{");
    }

    @Override
    public void emitIfEnd() {
        writeTarget("\n\t\t}");
    }

    @Override
    public void emitForBegin(String controlVar, String fromAssignVar, String toAssignVar, String stepAssignVar) {
        // Flat 模式：for 循环用原生 C++ 变量
        writeTarget("\n\t\tfor( " + controlVar + " = " + fromAssignVar + ";");
        writeTarget(controlVar + " <= " + toAssignVar + ";");
        if (stepAssignVar != null && !stepAssignVar.isEmpty()) {
            writeTarget(controlVar + " = " + controlVar + " + " + stepAssignVar + "){");
        } else {
            writeTarget(controlVar + "++){");
        }
    }

    @Override
    public void emitForEnd() {
        writeTarget("\n\t\t}");
    }

    @Override
    public void emitWhileBegin(String condAssignVar) {
        writeTarget("\n\t\twhile(" + condAssignVar + "){");
    }

    @Override
    public void emitWhileEnd() {
        writeTarget("\n\t\t}");
    }

    @Override
    public void emitRepeatBegin() {
        writeTarget("\n\t\tdo{");
    }

    @Override
    public void emitRepeatEnd(String condAssignVar) {
        writeTarget("\n\t\t}while(!(" + condAssignVar + "));");
    }

    @Override
    public void emitCaseBegin(String exprAssignVar) {
        writeTarget("\n\t\tswitch(" + exprAssignVar + "){");
    }

    @Override
    public void emitCaseOption(String value) {
        writeTarget("\n\t\t\tcase " + value + " :");
    }

    @Override
    public void emitCaseDefault() {
        writeTarget("\n\t\t\tdefault :");
    }

    @Override
    public void emitCaseEnd() {
        writeTarget("\n\t\t}");
    }

    @Override
    public void emitPrintStmt(String exprAssignVar) {
        writeTarget("\n\t\tprintf(\"%d\\n\", (int)(" + exprAssignVar + "));");
    }


    // ═══ 函数 / PROGRAM ═══

    @Override
    public void emitFuncDeclBegin(String funcName, String returnType, String params) {
        String nativeReturn = toNativeType(returnType);
        writeTarget("\n" + nativeReturn + " " + funcName + "(" + params + ") {");
    }

    @Override
    public void emitFuncDeclEnd() {
        writeTarget("\n}");
    }

    @Override
    public void emitFuncBodyBegin() {
        // Flat 模式下函数体直接在函数内
    }

    @Override
    public void emitFuncBodyEnd() {
        // Flat 模式下由 emitFuncDeclEnd 关闭
    }

    @Override
    public void emitFuncCall(String funcName, List<String> params) {
        StringBuilder sb = new StringBuilder();
        sb.append(funcName).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(params.get(i));
        }
        sb.append(")");
        writeTarget(sb.toString());
    }

    @Override
    public void emitProgDeclBegin(String progName) {
        writeTarget("\nvoid PROGRAM_" + progName + "(GVL& gvl, ProcessImage& io, TIME dt) {");
    }

    @Override
    public void emitProgDeclEnd() {
        writeTarget("\n}");
    }

    @Override
    public void emitProgBodyBegin() {
        // Flat 模式下 PROGRAM 体直接在函数内
    }

    @Override
    public void emitProgBodyEnd() {
        // Flat 模式下由 emitProgDeclEnd 关闭
    }


    // ═══ 函数块 ═══

    @Override
    public void emitFBBodyBegin() {
        // Flat 模式下 FB 体直接在函数内
    }

    @Override
    public void emitFBBodyEnd() {
        // Flat 模式下由 emitFuncDeclEnd 关闭
    }


    // ═══ 初始化 ═══

    @Override
    public void emitInitFuncBegin() {
        // Flat 模式不需要 initFunc，变量在 GVL 中
        writeTarget("\n// Flat mode: variables are in GVL, no initFunc needed\n");
    }

    @Override
    public void emitInitFuncEnd() {
        // 不需要
    }

    @Override
    public void emitInitFuncCall(String sentence) {
        // 不需要
    }


    // ═══ 底层输出 ═══

    @Override
    public void write(String code) {
        writeTarget(code);
    }


    // ═══ 辅助方法 ═══

    /**
     * 获取 GVL 偏移量定义（用于输出注释或头文件）
     */
    public String getOffsetDefinitions() {
        StringBuilder sb = new StringBuilder();
        sb.append("// GVL Offset Definitions\n");
        for (Map.Entry<String, Integer> entry : offsetMap.entrySet()) {
            String type = typeMap.get(entry.getKey());
            sb.append("// ").append(entry.getKey())
              .append(" : ").append(type)
              .append(" @ offset ").append(entry.getValue())
              .append("\n");
        }
        sb.append("// Total GVL usage: ").append(currentOffset).append(" bytes\n");
        return sb.toString();
    }

    public Map<String, Integer> getOffsetMap() {
        return Collections.unmodifiableMap(offsetMap);
    }

    public Map<String, String> getTypeMap() {
        return Collections.unmodifiableMap(typeMap);
    }
}
