package PLCTranslator;

import java.util.*;

/**
 * Flat 后端 — 生成 GVL 偏移量风格的 C++ 代码
 *
 * 使用新版运行时 rt_plc.h + rt_runtime.h，
 * 变量通过偏移量直接读写 GVL 内存，零堆分配、零虚函数。
 *
 * 所有 emit 方法返回代码字符串（不再直接写文件）。
 */
public class FlatCodeGenerator implements CodeGenerator {

    // GVL 偏移量分配
    private final Map<String, Integer> offsetMap = new LinkedHashMap<>();
    private final Map<String, String> typeMap = new LinkedHashMap<>();
    private int currentOffset = 0;

    // ST 类型名 → 原生 C++ 类型名
    private static final Map<String, String> TYPE_MAP = new HashMap<>();
    static {
        TYPE_MAP.put("SINT", "SINT");
        TYPE_MAP.put("INT", "INT");
        TYPE_MAP.put("DINT", "DINT");
        TYPE_MAP.put("LINT", "LINT");
        TYPE_MAP.put("USINT", "USINT");
        TYPE_MAP.put("UINT", "UINT");
        TYPE_MAP.put("UDINT", "UDINT");
        TYPE_MAP.put("ULINT", "ULINT");
        TYPE_MAP.put("REAL", "REAL");
        TYPE_MAP.put("LREAL", "LREAL");
        TYPE_MAP.put("BOOL", "BOOL");
        TYPE_MAP.put("STRING", "STRING");
        TYPE_MAP.put("TIME", "TIME");
        TYPE_MAP.put("DATE", "DATE");
        TYPE_MAP.put("TIME_OF_DAY", "TIME_OF_DAY");
        TYPE_MAP.put("DATE_AND_TIME", "DATE_AND_TIME");
        // PLC_Value 风格的类型名也映射
        TYPE_MAP.put("PLC_SINT_Value", "SINT");
        TYPE_MAP.put("PLC_INT_Value", "INT");
        TYPE_MAP.put("PLC_DINT_Value", "DINT");
        TYPE_MAP.put("PLC_LINT_Value", "LINT");
        TYPE_MAP.put("PLC_Real_Value", "REAL");
        TYPE_MAP.put("PLC_LReal_Value", "LREAL");
        TYPE_MAP.put("PLC_Bool_Value", "BOOL");
        TYPE_MAP.put("PLC_String_Value", "STRING");
    }

    // 类型 → 字节大小
    private static final Map<String, Integer> SIZE_MAP = new HashMap<>();
    static {
        SIZE_MAP.put("SINT", 1);
        SIZE_MAP.put("INT", 2);
        SIZE_MAP.put("DINT", 4);
        SIZE_MAP.put("LINT", 8);
        SIZE_MAP.put("USINT", 1);
        SIZE_MAP.put("UINT", 2);
        SIZE_MAP.put("UDINT", 4);
        SIZE_MAP.put("ULINT", 8);
        SIZE_MAP.put("REAL", 4);
        SIZE_MAP.put("LREAL", 8);
        SIZE_MAP.put("BOOL", 1);
        SIZE_MAP.put("STRING", 256);
        SIZE_MAP.put("TIME", 8);
        SIZE_MAP.put("DATE", 4);
        SIZE_MAP.put("TIME_OF_DAY", 8);
        SIZE_MAP.put("DATE_AND_TIME", 8);
    }

    private String toNativeType(String typeName) {
        String mapped = TYPE_MAP.get(typeName);
        return mapped != null ? mapped : typeName;
    }

    private int getTypeSize(String nativeType) {
        Integer size = SIZE_MAP.get(nativeType);
        return size != null ? size : 4; // 默认 4 字节
    }

    /**
     * 为变量分配 GVL 偏移量
     */
    private int allocateOffset(String varName, String nativeType) {
        int size = getTypeSize(nativeType);
        // 对齐到类型大小
        int aligned = (currentOffset + size - 1) / size * size;
        offsetMap.put(varName, aligned);
        typeMap.put(varName, nativeType);
        currentOffset = aligned + size;
        return aligned;
    }

    /**
     * 获取变量的 GVL 读取表达式
     */
    private String readExpr(String varName) {
        String type = typeMap.get(varName);
        Integer offset = offsetMap.get(varName);
        if (type == null || offset == null) {
            // 未知变量，可能是临时变量或表达式结果，直接返回
            return varName;
        }
        return "gvl.read<" + type + ">(" + offset + ")";
    }

    /**
     * 获取变量的 GVL 写入语句前缀
     */
    private String writeExpr(String varName, String valueExpr) {
        String type = typeMap.get(varName);
        Integer offset = offsetMap.get(varName);
        if (type == null || offset == null) {
            return varName + " = " + valueExpr;
        }
        return "gvl.write<" + type + ">(" + offset + ", " + valueExpr + ")";
    }


    // ═══ 文件头尾 ═══

    @Override
    public String emitHeader() {
        return "// Generated by ST2C++ (Flat backend)\n"
                + "#include \"rt_plc.h\"\n"
                + "#include \"rt_runtime.h\"\n"
                + "\nusing namespace rt_plc;\n\n";
    }

    @Override
    public String emitFooter() {
        return ""; // Flat 模式不需要特殊清理
    }


    // ═══ 变量声明 ═══

    @Override
    public String emitVarDecl(String name, String typeName, String assignVar) {
        String nativeType = toNativeType(typeName);
        allocateOffset(name, nativeType);
        // Flat 模式：变量在 GVL 中，不需要 C++ 声明
        // 但如果需要初始化，生成初始化代码
        if (assignVar != null && !assignVar.isEmpty() && !"0".equals(assignVar) && !"\"\"".equals(assignVar)) {
            return "\n\t\t" + writeExpr(name, assignVar) + ";";
        }
        return "";
    }

    @Override
    public String emitGlobalVarDecl(String name, String typeName, String assignVar, String varSection) {
        String nativeType = toNativeType(typeName);
        allocateOffset(name, nativeType);
        // 全局变量在 GVL 中，不需要 C++ 声明
        return "";
    }

    @Override
    public String emitProgVarDecl(String name, String typeName, String assignVar) {
        String nativeType = toNativeType(typeName);
        allocateOffset(name, nativeType);
        // PROGRAM 变量在 GVL 中
        return "";
    }


    // ═══ 赋值 ═══

    @Override
    public String emitAssign(String varName, String exprAssignVar) {
        return "\n\t\t" + writeExpr(varName, exprAssignVar) + ";";
    }

    @Override
    public String emitFuncReturnAssign(String exprAssignVar) {
        return "\n\t\treturn " + exprAssignVar + ";";
    }


    // ═══ 控制流 ═══

    @Override
    public String emitIfBegin(String condAssignVar) {
        return "\n\t\tif(" + condAssignVar + "){";
    }

    @Override
    public String emitElseIf(String condAssignVar) {
        return "\n\t\t}else if(" + condAssignVar + "){";
    }

    @Override
    public String emitElse() {
        return "\n\t\t}else{";
    }

    @Override
    public String emitIfEnd() {
        return "\n\t\t}";
    }

    @Override
    public String emitForBegin(String controlVar, String fromAssignVar, String toAssignVar, String stepAssignVar) {
        StringBuilder sb = new StringBuilder();
        // Flat 模式：for 循环用原生 C++ 变量
        sb.append("\n\t\tfor( ").append(controlVar).append(" = ").append(fromAssignVar).append(";");
        sb.append(controlVar).append(" <= ").append(toAssignVar).append(";");
        if (stepAssignVar != null && !stepAssignVar.isEmpty()) {
            sb.append(controlVar).append(" = ").append(controlVar).append(" + ").append(stepAssignVar).append("){");
        } else {
            sb.append(controlVar).append("++){");
        }
        return sb.toString();
    }

    @Override
    public String emitForEnd() {
        return "\n\t\t}";
    }

    @Override
    public String emitWhileBegin(String condAssignVar) {
        return "\n\t\twhile(" + condAssignVar + "){";
    }

    @Override
    public String emitWhileEnd() {
        return "\n\t\t}";
    }

    @Override
    public String emitRepeatBegin() {
        return "\n\t\tdo{";
    }

    @Override
    public String emitRepeatEnd(String condAssignVar) {
        return "\n\t\t}while(!(" + condAssignVar + "));";
    }

    @Override
    public String emitCaseBegin(String exprAssignVar) {
        return "\n\t\tswitch(" + exprAssignVar + "){";
    }

    @Override
    public String emitCaseOption(String value) {
        return "\n\t\t\tcase " + value + " :";
    }

    @Override
    public String emitCaseDefault() {
        return "\n\t\t\tdefault :";
    }

    @Override
    public String emitCaseEnd() {
        return "\n\t\t}";
    }

    @Override
    public String emitPrintStmt(String exprAssignVar) {
        return "\n\t\tprintf(\"%d\\n\", (int)(" + exprAssignVar + "));";
    }


    // ═══ 函数 / PROGRAM ═══

    @Override
    public String emitFuncDeclBegin(String funcName, String returnType, String params) {
        String nativeReturn = toNativeType(returnType);
        return "\n" + nativeReturn + " " + funcName + "(" + params + ") {";
    }

    @Override
    public String emitFuncDeclEnd() {
        return "\n}";
    }

    @Override
    public String emitFuncBodyBegin() {
        return ""; // Flat 模式下函数体直接在函数内
    }

    @Override
    public String emitFuncBodyEnd() {
        return ""; // Flat 模式下由 emitFuncDeclEnd 关闭
    }

    @Override
    public String emitFuncCall(String funcName, List<String> params) {
        StringBuilder sb = new StringBuilder();
        sb.append(funcName).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(params.get(i));
        }
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String emitProgDeclBegin(String progName) {
        return "\nvoid PROGRAM_" + progName + "(GVL& gvl, ProcessImage& io, TIME dt) {";
    }

    @Override
    public String emitProgDeclEnd() {
        return "\n}";
    }

    @Override
    public String emitProgBodyBegin() {
        return ""; // Flat 模式下 PROGRAM 体直接在函数内
    }

    @Override
    public String emitProgBodyEnd() {
        return ""; // Flat 模式下由 emitProgDeclEnd 关闭
    }


    // ═══ 函数块 ═══

    @Override
    public String emitFBBodyBegin() {
        return ""; // Flat 模式下 FB 体直接在函数内
    }

    @Override
    public String emitFBBodyEnd() {
        return ""; // Flat 模式下由 emitFuncDeclEnd 关闭
    }


    // ═══ 初始化 ═══

    @Override
    public String emitInitFuncBegin() {
        return "\n// Flat mode: variables are in GVL, no initFunc needed\n";
    }

    @Override
    public String emitInitFuncEnd() {
        return ""; // 不需要
    }

    @Override
    public String emitInitFuncCall(String sentence) {
        return ""; // 不需要
    }


    // ═══ 底层输出 ═══

    @Override
    public String write(String code) {
        return code;
    }


    // ═══ 辅助方法 ═══

    /**
     * 获取 GVL 偏移量定义（用于输出注释或头文件）
     */
    public String getOffsetDefinitions() {
        StringBuilder sb = new StringBuilder();
        sb.append("// GVL Offset Definitions\n");
        for (Map.Entry<String, Integer> entry : offsetMap.entrySet()) {
            String type = typeMap.get(entry.getKey());
            sb.append("// ").append(entry.getKey())
              .append(" : ").append(type)
              .append(" @ offset ").append(entry.getValue())
              .append("\n");
        }
        sb.append("// Total GVL usage: ").append(currentOffset).append(" bytes\n");
        return sb.toString();
    }

    public Map<String, Integer> getOffsetMap() {
        return Collections.unmodifiableMap(offsetMap);
    }

    public Map<String, String> getTypeMap() {
        return Collections.unmodifiableMap(typeMap);
    }
}
