package PLCTranslator;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class GvlContext {

    // GVL 偏移量分配
    public final Map<String, Integer> offsetMap = new LinkedHashMap<>();
    public final Map<String, String> typeMap = new LinkedHashMap<>();
    // 数组变量的维度信息：变量名 → 每个维度 [lower, upper, count]
    public final Map<String, int[][]> arrayBoundsMap = new LinkedHashMap<>();
    // 数组元素类型：变量名 → 元素类型名
    public final Map<String, String> arrayElemTypeMap = new LinkedHashMap<>();
    public int currentOffset = 0;

    // ─── Direct-access mode（union 方案）───
    // 记录每个 GVL 变量所属的 PROGRAM（null 表示全局）
    public final Map<String, String> varProgramMap = new HashMap<>();
    private String currentProgram = null;

    public void setCurrentProgram(String progName) {
        currentProgram = progName;
    }

    public String getMangledName(String varName) {
        String id = fileId.isEmpty() ? "" : fileId + "$";
        String prog = varProgramMap.get(varName);
        if (prog != null && !prog.isEmpty()) {
            return id + prog + "$" + varName;
        } else {
            return id + "gbl$" + varName;
        }
    }

    /**
     * 生成 gvl_layout.gen.h — 仅用于 reinterpret_cast 做直接成员访问
     */
    public String emitGVLLayoutHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated GVL layout struct — for direct member access\n");
        sb.append("// DO NOT EDIT — generated by ST2C++ compiler\n");
        sb.append("#pragma once\n");
        sb.append("#include \"core/gvl.h\"\n\n");
        sb.append("namespace rt_plc {\n\n");
        sb.append("struct GVL_LAYOUT {\n");
        for (String varName : offsetMap.keySet()) {
            String type = typeMap.get(varName);
            if (type == null) continue;
            if (ioVarMap.containsKey(varName)) continue;
            if (type.startsWith("ARRAY[")) {
                String elemType = arrayElemTypeMap.get(varName);
                int[][] bounds = arrayBoundsMap.get(varName);
                int total = (bounds != null) ? bounds[0][2] : 0;
                sb.append("    ").append(elemType).append(" ")
                  .append(getMangledName(varName)).append("[").append(total).append("];\n");
            } else {
                sb.append("    ").append(type).append(" ")
                  .append(getMangledName(varName)).append(";\n");
            }
        }
        sb.append("};\n\n");
        sb.append("inline GVL_LAYOUT& gvl_layout(GVL& gvl) {\n");
        sb.append("    return *reinterpret_cast<GVL_LAYOUT*>(gvl.memory);\n");
        sb.append("}\n\n");
        sb.append("} // namespace rt_plc\n");
        return sb.toString();
    }

    // ─── Struct 类型支持 ───
    public final Map<String, StructLayout> structLayoutMap = new HashMap<>();

    // ─── Enum 类型支持 ───
    public final Map<String, String> enumNameToUnderlying = new HashMap<>();
    public final Map<String, String> enumRuntimeToUnderlying = new HashMap<>();

    // ─── I/O 映射变量支持 ───
    public enum IODirection { INPUT, OUTPUT, MEMORY }

    public static class IOInfo {
        public IODirection dir;
        public int byteOffset;
        public int bitOffset = -1;
        public String typeName;
        public IOInfo() {}
        public IOInfo(IODirection dir, int byteOffset, int bitOffset, String typeName) {
            this.dir = dir; this.byteOffset = byteOffset;
            this.bitOffset = bitOffset; this.typeName = typeName;
        }
    }

    public final Map<String, IOInfo> ioVarMap = new LinkedHashMap<>();

    // ─── POU 注册表 ───
    public final List<String> programNames = new ArrayList<>();
    public final Set<String> programNameSet = new HashSet<>();
    public String fileId = "";

    public void addProgramName(String name) {
        if (programNameSet.contains(name)) {
            throw new RuntimeException("Duplicate PROGRAM definition: " + name);
        }
        programNames.add(name);
        programNameSet.add(name);
    }

    public String mangleProgName(String progName) {
        return fileId.isEmpty() ? progName : fileId + "_" + progName;
    }

    public void setFileId(String id) {
        this.fileId = id;
    }

    public String getFileId() {
        return fileId.isEmpty() ? "unnamed" : fileId;
    }

    public List<String> getProgramNames() {
        return Collections.unmodifiableList(programNames);
    }

    // ─── FOR 循环 GVL 局部变量遮盖 ───
    public final Set<String> shadowedGvlVars = new HashSet<>();
    public final Set<String> locallyDeclaredGvlVars = new HashSet<>();
    public static class ShadowEntry {
        public String varName; public String type; public int offset;
        public ShadowEntry(String v, String t, int o) { varName = v; type = t; offset = o; }
    }
    public final ArrayDeque<ShadowEntry> shadowStack = new ArrayDeque<>();

    // ─── Struct/Field 类型（原 CodeGenerator 内） ───
    public static class StructField {
        public String name;
        public String type;
        public int offset;
        public StructField(String name, String type, int offset) {
            this.name = name; this.type = type; this.offset = offset;
        }
    }

    public static class StructLayout {
        public String structName;
        public List<StructField> fields;
        public int totalSize;
        public StructLayout(String structName, List<StructField> fields, int totalSize) {
            this.structName = structName;
            this.fields = fields;
            this.totalSize = totalSize;
        }
    }

    public void registerStructType(String typeName, StructLayout layout) {
        structLayoutMap.put(typeName, layout);
        SIZE_MAP.put(typeName, layout.totalSize);
    }

    public void registerEnumType(String enumName, String runtimeTypeName, String underlyingNativeType) {
        enumNameToUnderlying.put(enumName, underlyingNativeType);
        enumRuntimeToUnderlying.put(runtimeTypeName, underlyingNativeType);
    }

    public Integer getStructFieldOffset(String structTypeName, String fieldName) {
        StructLayout layout = structLayoutMap.get(structTypeName);
        if (layout == null) return null;
        for (StructField f : layout.fields) {
            if (f.name.equals(fieldName)) return f.offset;
        }
        return null;
    }

    public String getStructFieldType(String structTypeName, String fieldName) {
        StructLayout layout = structLayoutMap.get(structTypeName);
        if (layout == null) return null;
        for (StructField f : layout.fields) {
            if (f.name.equals(fieldName)) return f.type;
        }
        return null;
    }

    public Integer getVarOffset(String varName) {
        return offsetMap.get(varName);
    }

    public String getVarType(String varName) {
        return typeMap.get(varName);
    }

    /**
     * 解析结构体成员的绝对 GVL 偏移量。
     * 例如 memberName="Srv"，遍历所有 GVL 变量找到包含 Srv 的结构体，
     * 返回 baseOffset + fieldOffset。
     */
    public Integer resolveStructMemberOffset(String memberName) {
        for (Map.Entry<String, Integer> entry : offsetMap.entrySet()) {
            String varName = entry.getKey();
            Integer baseOffset = entry.getValue();
            String typeName = typeMap.get(varName);
            if (typeName == null) continue;
            Integer fieldOff = getStructFieldOffset(typeName, memberName);
            if (fieldOff != null) {
                return baseOffset + fieldOff;
            }
        }
        return null;
    }

    // ST 类型名 → 原生 C++ 类型名
    public static final Map<String, String> TYPE_MAP = new HashMap<>();
    static {
        TYPE_MAP.put("SINT", "SINT");
        TYPE_MAP.put("INT", "INT");
        TYPE_MAP.put("DINT", "DINT");
        TYPE_MAP.put("LINT", "LINT");
        TYPE_MAP.put("USINT", "USINT");
        TYPE_MAP.put("UINT", "UINT");
        TYPE_MAP.put("UDINT", "UDINT");
        TYPE_MAP.put("ULINT", "ULINT");
        TYPE_MAP.put("BYTE", "BYTE");
        TYPE_MAP.put("WORD", "WORD");
        TYPE_MAP.put("DWORD", "DWORD");
        TYPE_MAP.put("LWORD", "LWORD");
        TYPE_MAP.put("REAL", "REAL");
        TYPE_MAP.put("LREAL", "LREAL");
        TYPE_MAP.put("BOOL", "BOOL");
        TYPE_MAP.put("STRING", "STRING");
        TYPE_MAP.put("TIME", "TIME");
        TYPE_MAP.put("DATE", "DATE");
        TYPE_MAP.put("TIME_OF_DAY", "TIME_OF_DAY");
        TYPE_MAP.put("DATE_AND_TIME", "DATE_AND_TIME");
        TYPE_MAP.put("PLC_SINT_Value", "SINT");
        TYPE_MAP.put("PLC_INT_Value", "INT");
        TYPE_MAP.put("PLC_DINT_Value", "DINT");
        TYPE_MAP.put("PLC_LINT_Value", "LINT");
        TYPE_MAP.put("PLC_Real_Value", "REAL");
        TYPE_MAP.put("PLC_LReal_Value", "LREAL");
        TYPE_MAP.put("PLC_Bool_Value", "BOOL");
        TYPE_MAP.put("PLC_String_Value", "STRING");
    }

    // 类型 → 字节大小
    public static final Map<String, Integer> SIZE_MAP = new HashMap<>();
    private static void initSizeMap() {
        SIZE_MAP.put("SINT", 1);
        SIZE_MAP.put("INT", 2);
        SIZE_MAP.put("DINT", 4);
        SIZE_MAP.put("LINT", 8);
        SIZE_MAP.put("USINT", 1);
        SIZE_MAP.put("UINT", 2);
        SIZE_MAP.put("UDINT", 4);
        SIZE_MAP.put("ULINT", 8);
        SIZE_MAP.put("BYTE", 1);
        SIZE_MAP.put("WORD", 2);
        SIZE_MAP.put("DWORD", 4);
        SIZE_MAP.put("LWORD", 8);
        SIZE_MAP.put("REAL", 4);
        SIZE_MAP.put("LREAL", 8);
        SIZE_MAP.put("BOOL", 1);
        SIZE_MAP.put("STRING", 256);
        SIZE_MAP.put("TIME", 8);
        SIZE_MAP.put("DATE", 4);
        SIZE_MAP.put("TIME_OF_DAY", 8);
        SIZE_MAP.put("DATE_AND_TIME", 8);
    }
    static { initSizeMap(); }

    public static void resetStatic() {
        SIZE_MAP.clear();
        initSizeMap();
    }

    public String toNativeType(String typeName) {
        if (typeName == null) return typeName;
        String mapped = TYPE_MAP.get(typeName);
        if (mapped != null) return mapped;
        return typeName;
    }

    /**
     * 查询类型在 GVL 中占用的字节数。
     *
     * @param typeName 类型名——可以是 ST 原始类型（如 "TIME"），
     *                 也可以是 C++ 原生类型（如 "UINT", "MY_STRUCT"）。
     *                 方法内部会先尝试映射为 C++ 原生类型，再查大小。
     * @return 该类型占用的字节数，未知时默认返回 4
     */
    public int getTypeSize(String typeName) {
        if (typeName == null)  throw new IllegalArgumentException("typeName cannot be null");
        // 先统一转换为 C++ 原生类型名（例如 "TIME" → "UINT"）
        String nativeType = toNativeType(typeName);
        Integer size = SIZE_MAP.get(nativeType);
        if (size != null) return size;
        StructLayout layout = structLayoutMap.get(nativeType);
        if (layout != null) return layout.totalSize;
        String underlying = enumNameToUnderlying.get(nativeType);
        if (underlying != null) return getTypeSize(underlying);
        // 运行时枚举类型名（如 "PLC_Enum_Value<2938>"）→ 底层类型
        underlying = enumRuntimeToUnderlying.get(nativeType);
        if (underlying != null) return getTypeSize(underlying);
        ArrayInfo arrayInfo = parseArrayType(nativeType);
        if (arrayInfo != null) {
            return arrayInfo.count * getTypeSize(arrayInfo.elemType);
        }
        throw new IllegalArgumentException("Unknown type: " + typeName);
    }

    public int allocateOffset(String varName, String nativeType) {
        int size = getTypeSize(nativeType);
        int aligned = (currentOffset + size - 1) / size * size;
        offsetMap.put(varName, aligned);
        typeMap.put(varName, nativeType);
        varProgramMap.put(varName, currentProgram);
        currentOffset = aligned + size;
        return aligned;
    }

    /**
     * 分配数组变量的 GVL 偏移量，同时注册 bounds 和 elemType 信息。
     * 封装了 offset/type/arrayBounds/arrayElemType 四个 map 的写入。
     */
    public int allocateArrayOffset(String varName, int totalCount,
                                   String elemTypeNative, int[][] arrayBounds) {
        int elemSize = getTypeSize(elemTypeNative);
        int totalSize = elemSize * totalCount;
        int aligned = (currentOffset + elemSize - 1) / elemSize * elemSize;
        offsetMap.put(varName, aligned);
        typeMap.put(varName, "ARRAY[" + totalCount + "] OF " + elemTypeNative);
        arrayBoundsMap.put(varName, arrayBounds);
        arrayElemTypeMap.put(varName, elemTypeNative);
        varProgramMap.put(varName, currentProgram);
        currentOffset = aligned + totalSize;
        return aligned;
    }

    // ═══ I/O 映射变量支持 ═══

    public IOInfo parseATAddress(String location) {
        if (location == null || !location.startsWith("%")) return null;
        IOInfo info = new IOInfo();
        int pos = 1;
        info.dir = IODirection.INPUT;
        if (pos < location.length()) {
            char c = location.charAt(pos);
            if (c == 'I' || c == 'Q' || c == 'M') {
                info.dir = (c == 'I') ? IODirection.INPUT
                        : (c == 'Q') ? IODirection.OUTPUT : IODirection.MEMORY;
                pos++;
            }
        }
        int sizeInBytes = 1;
        boolean isBit = false;
        if (pos < location.length()) {
            char c = location.charAt(pos);
            if (c == 'X') { isBit = true; sizeInBytes = 0; pos++; }
            else if (c == 'B') { pos++; }
            else if (c == 'W') { sizeInBytes = 2; pos++; }
            else if (c == 'D') { sizeInBytes = 4; pos++; }
            else if (c == 'L') { sizeInBytes = 8; pos++; }
        }
        StringBuilder numStr = new StringBuilder();
        while (pos < location.length() && Character.isDigit(location.charAt(pos))) {
            numStr.append(location.charAt(pos));
            pos++;
        }
        if (numStr.length() == 0) return null;
        int value = Integer.parseInt(numStr.toString());
        int bitOffset = -1;
        if (pos < location.length() && location.charAt(pos) == '.') {
            pos++;
            StringBuilder bitStr = new StringBuilder();
            while (pos < location.length() && Character.isDigit(location.charAt(pos))) {
                bitStr.append(location.charAt(pos));
                pos++;
            }
            if (bitStr.length() > 0) bitOffset = Integer.parseInt(bitStr.toString());
        }
        if (isBit) {
            info.byteOffset = value;
            info.bitOffset = (bitOffset >= 0) ? bitOffset : 0;
        } else {
            info.byteOffset = value * sizeInBytes;
            info.bitOffset = -1;
        }
        return info;
    }

    public void registerIOVariable(String varName, String typeName, String location) {
        if (varName == null || location == null) return;
        String cleanName = varName.startsWith("*") ? varName.substring(1) : varName;
        IOInfo info = parseATAddress(location);
        if (info == null) {
            throw new RuntimeException("Invalid AT address: " + location + " for variable " + varName);
        }
        if (info.dir == IODirection.MEMORY) {
            return;
        }
        info.typeName = toNativeType(typeName);
        ioVarMap.put(cleanName, info);
    }

    public boolean isIOVariable(String varName) {
        if (varName == null) return false;
        String cleanName = varName.startsWith("*") ? varName.substring(1) : varName;
        return ioVarMap.containsKey(cleanName);
    }

    public String emitIORead(String varName) {
        if (varName == null) return null;
        String cleanName = varName.startsWith("*") ? varName.substring(1) : varName;
        IOInfo info = ioVarMap.get(cleanName);
        if (info == null) return null;
        if (info.dir == IODirection.MEMORY) return null;
        String prefix = (info.dir == IODirection.INPUT) ? "io.readInput" : "io.readOutput";
        if (info.bitOffset >= 0) {
            return prefix + "Bit(" + info.byteOffset + ", " + info.bitOffset + ")";
        }
        return prefix + "<" + info.typeName + ">(" + info.byteOffset + ")";
    }

    public String emitIOWrite(String varName, String valueExpr) {
        if (varName == null) return null;
        String cleanName = varName.startsWith("*") ? varName.substring(1) : varName;
        IOInfo info = ioVarMap.get(cleanName);
        if (info == null) return null;
        if (info.dir == IODirection.MEMORY) return null;
        if (info.bitOffset >= 0) {
            return "io.writeOutputBit(" + info.byteOffset + ", " + info.bitOffset + ", " + valueExpr + ")";
        }
        return "io.writeOutput<" + info.typeName + ">(" + info.byteOffset + ", " + valueExpr + ")";
    }

    // ═══ 数组类型信息 ═══

    public static class ArrayInfo {
        public int count;
        public String elemType;
    }

    public ArrayInfo parseArrayType(String typeName) {
        if (typeName == null || !typeName.startsWith("ARRAY[")) return null;
        java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(
            "ARRAY\\[(\\d+)\\]\\s+OF\\s+(\\w+)");
        java.util.regex.Matcher matcher = pattern.matcher(typeName);
        if (matcher.find()) {
            ArrayInfo info = new ArrayInfo();
            info.count = Integer.parseInt(matcher.group(1));
            info.elemType = matcher.group(2);
            return info;
        }
        return null;
    }

    public String getOffsetDefinitions() {
        StringBuilder sb = new StringBuilder();
        sb.append("// GVL Offset Definitions\n");
        for (Map.Entry<String, Integer> entry : offsetMap.entrySet()) {
            String type = typeMap.get(entry.getKey());
            sb.append("// ").append(entry.getKey())
              .append(" : ").append(type)
              .append(" @ offset ").append(entry.getValue())
              .append("\n");
        }
        sb.append("// Total GVL usage: ").append(currentOffset).append(" bytes\n");
        return sb.toString();
    }
     /**
     * @deprecated 请改用 visitor 路径 (t.visit(ctx)) 翻译表达式。
     *             此方法仅用于常量等简单字符串的正则替换，新代码不应再调用。只是给一个测试用例调用
     */
    @Deprecated
    public String emitPOURegistration(String fileId, List<String> progNames) {
        if (progNames == null || progNames.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("\n// ─── Auto-generated POU Registration (").append(fileId).append(") ───\n");
        sb.append("void registerPOU_").append(fileId).append("(POURegistry& reg) {\n");
        for (String name : progNames) {
            String mangled = mangleProgName(name);
            sb.append("    POUCallbacks cbs;\n");
            sb.append("    cbs.init = PROGRAM_").append(mangled).append("_init;\n");
            sb.append("    cbs.cyclic = PROGRAM_").append(mangled).append("_cyclic;\n");
            sb.append("    cbs.pre = PROGRAM_").append(mangled).append("_pre;\n");
            sb.append("    cbs.post = PROGRAM_").append(mangled).append("_post;\n");
            sb.append("    reg.add(\"").append(name).append("\", cbs);\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    /**
     * @deprecated 请改用 visitor 路径 (t.visit(ctx)) 翻译表达式。
     *             此方法仅用于常量等简单字符串的正则替换，新代码不应再调用。
     */
    @Deprecated
    public String translateExpr(String expr) {
        if (expr == null || expr.isEmpty()) {
            return expr;
        }

        String result = expr;
        boolean changed = true;
        int maxRounds = 10;
        while (changed && maxRounds-- > 0) {
            changed = false;

            // 5. 数组元素访问
            String arrayAccessPattern = "([A-Z][A-Z0-9$_]*)\\[(.*?)\\]";
            Matcher arrayAccessMatcher = Pattern.compile(arrayAccessPattern).matcher(result);
            StringBuilder sb = new StringBuilder();
            while (arrayAccessMatcher.find()) {
                changed = true;
                String arrName = arrayAccessMatcher.group(1);
                String indexExpr = arrayAccessMatcher.group(2);
                String arrType = typeMap.get(arrName);
                Integer arrOffset = offsetMap.get(arrName);
                if (arrType != null && arrType.startsWith("ARRAY[") && arrOffset != null) {
                    Pattern typePattern = Pattern.compile("ARRAY\\[(\\d+)\\] OF (\\w+)");
                    Matcher typeMatcher = typePattern.matcher(arrType);
                    if (typeMatcher.find()) {
                        String elemType = typeMatcher.group(2);
                        int count = Integer.parseInt(typeMatcher.group(1));
                        String translatedIndex = translateExpr(indexExpr);
                        arrayAccessMatcher.appendReplacement(sb,
                            Matcher.quoteReplacement("gv." + getMangledName(arrName)) + "[" + translatedIndex + "]");
                        continue;
                    }
                }
                arrayAccessMatcher.appendReplacement(sb, arrayAccessMatcher.group(0));
            }
            arrayAccessMatcher.appendTail(sb);
            result = sb.toString();

            if (!changed) break;
        }

        // 6. 清理残余解引用星号和地址运算符
        result = result.replaceAll("\\(\\*([A-Za-z_]\\w*)\\)", "($1)");
        result = result.replaceAll("(?<![\\w*+\\-/<>])\\*([A-Za-z_]\\w*)(?![\\w*+\\-/<>])", "$1");
        result = result.replace("( *", "(");
        result = result.replace("*this->returnValue", "returnValue");
        result = result.replaceAll("(?<![\\w*+\\-/<>])&([A-Za-z_]\\w*)(?![\\w*+\\-/<>])", "$1");
        result = result.replace("( &", "(");

        // 7. GVL 变量替换
        for (String varName : offsetMap.keySet()) {
            String type = typeMap.get(varName);
            if (type == null) continue;
            if (type.startsWith("ARRAY[")) continue;
            if (shadowedGvlVars.contains(varName)) continue;
            if (ioVarMap.containsKey(varName)) continue;
            String regex = "(?<![A-Za-z0-9_])" + Pattern.quote(varName) + "(?![A-Za-z0-9_])";
            result = result.replaceAll(regex, Matcher.quoteReplacement("gv." + getMangledName(varName)));
        }

        // 7b. I/O 映射变量替换
        for (String varName : ioVarMap.keySet()) {
            if (shadowedGvlVars.contains(varName)) continue;
            String ioRead = emitIORead(varName);
            if (ioRead != null) {
                String regex = "(?<![A-Za-z0-9_])" + Pattern.quote(varName) + "(?![A-Za-z0-9_])";
                result = result.replaceAll(regex, ioRead);
            }
        }

        return result;
    }

    public Map<String, Integer> getOffsetMap() {
        return Collections.unmodifiableMap(offsetMap);
    }

    public Map<String, String> getTypeMap() {
        return Collections.unmodifiableMap(typeMap);
    }
}
