#!/usr/bin/env bash
set -euo pipefail

# HVAC Controller — 集成测试编译运行脚本 (Linux/macOS)
# Usage: ./run.sh [--build-jar]

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ST2C_HOME="$(cd "$PROJECT_DIR/../../.." && pwd)"
STDLIB="$ST2C_HOME/examples/iec_stdlib.st"
JAR="$ST2C_HOME/java/target/st2c-jar-with-dependencies.jar"
OUTPUT_DIR="$ST2C_HOME/output/flat/build"

# Detect platform for target selection
UNAME="$(uname -s)"
case "$UNAME" in
    Linux*)  TARGET="linux"  ;;
    Darwin*) TARGET="desktop" ;;
    *)       TARGET="desktop" ;;
esac

echo "=========================================="
echo " HVAC Controller — Integration Test"
echo " Platform: $(uname -s) → target/$TARGET"
echo "=========================================="

# Step 1: Build JAR if needed
if [ "${1:-}" = "--build-jar" ]; then
    echo "[1/4] Building Java compiler JAR..."
    (cd "$ST2C_HOME/java" && mvn package -DskipTests)
fi

if [ ! -f "$JAR" ]; then
    echo "ERROR: JAR not found at $JAR"
    echo "Run with --build-jar to compile first, or build manually:"
    echo "  cd java && mvn package -DskipTests"
    exit 1
fi

echo "[1/4] JAR ready"

# Step 2: Compile ST files
echo "[2/4] Compiling ST sources..."
mkdir -p "$OUTPUT_DIR"

java -jar "$JAR" \
    --stdlib "$STDLIB" \
    --input "$PROJECT_DIR/types.st" \
    --input "$PROJECT_DIR/io_config.st" \
    --input "$PROJECT_DIR/pid_func.st" \
    --input "$PROJECT_DIR/zone_fb.st" \
    --input "$PROJECT_DIR/main.st" \
    --output-dir "$OUTPUT_DIR" \
    --file-id hvac \
    --verbose

echo "[2/4] Compilation complete"

# Step 3: Build runtime with POU (registry auto-generated by Makefile)
echo "[3/4] Building runtime (target/$TARGET)..."
make -C "$ST2C_HOME/target/$TARGET" all
echo "[3/4] Build complete"

# Step 4: Run integration test
echo "[4/4] Running HVAC integration test..."
"$ST2C_HOME/target/$TARGET/plc_runtime_$TARGET"

echo "[4/4] Execution complete"

echo "=========================================="
echo " SUCCESS: HVAC integration test passed"
echo "=========================================="
